[package]
name = "benchmark-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Vulnerable or old dependencies to test dependency scanning
smallvec = "1.6.0"
hyper = "0.14.9"
regex = "1.5.4"
time = "0.1.44"
tokio = "1.8.0"
actix-web = "3.3.2"
serde_json = "1.0.50"
md5 = "0.7.0"
reqwest = "0.10.0"
